# "service" is the name of this project. This will also be added to your AWS resource names.
service: dio-liver-serverless-project
frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:GetItem
            - dynamodb:scan
          Resource:
            - arn:aws:dynamodb:us-east-1:579254390465:table/ItemTableNew    
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - s3:PutObject
        - s3:ListBucket
        - s3:GetObject
      Resource:
        - "arn:aws:s3:::upload-bucket-dio-liver-serverless"
        - "arn:aws:s3:::upload-bucket-dio-liver-serverless/*"           
  apiGateway:
    binaryMediaTypes:
      - multipart/form-data      

functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          path: /
          method: get

  insertItem:
    handler: src/insertItem.handler
    events: 
      - http:
          path: /item
          method: post
  fetchItems:
    handler: src/fetchItems.handler
    events: 
      - http:
          path: /item
          method: get         
  fetchItem:
    handler: src/fetchItem.handler
    events: 
      - http:
          path: /item/{id}
          method: get 
  updateItem:
    handler: src/updateItem.handler
    events: 
      - http:
          path: /items/{id}
          method: put    
  uploadFile:
    handler: src/uploadFile.handler
    events:
      - http:
          path: /upload
          method: post
          cors: true 
          request:
            contentHandling: CONVERT_TO_BINARY # <- converte o corpo para binário
  listFiles:
    handler: src/listFiles.handler
    events:
      - http:
          path: /files
          method: get          

package:
  individually: true

resources:
  Resources:
    ItemTableNew:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ItemTableNew
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
    UploadBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: upload-bucket-dio-liver-serverless
